app:
  name: "ProfitScout API"
  version: "1.0"
  env: "local"  # Change to "production" when deploying to Cloud Run

gcloud:
  project_id: "aialchemy"
  region: "us-central1"

bigquery:
  stock_table: "aialchemy.financial_data.sp500_metadata"
  ratios_table: "aialchemy.financial_data.financial_ratios"

gemini:
  model: "gemini-1.5-pro"
  api_key: "${GEMINI_API_KEY}"  # Loaded from Google Secret Manager or .env

logging:
  level: "DEBUG"
  log_file: "logs/app.log"

security:
  enable_rate_limiting: true
  max_requests_per_minute: 10
